# Generated by Django 4.1.5 on 2023-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100)),
                ('frontEnd', models.CharField(max_length=100)),
                ('backEnd', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
