# Generated by Django 4.1.5 on 2023-03-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_researchpaper_researchcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchcomment',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='researchcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='researchcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ResearchComment',
        ),
        migrations.DeleteModel(
            name='ResearchPaper',
        ),
    ]
